name: Continuous Integration & Delivery
on:
  push:
    branches:
      - '*'
      - '*/*'
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build --info
        env:
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ secrets.CI_TOKEN }}
      - name: Publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ secrets.CI_TOKEN }}
      - name: Delete Past Workflows
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Delete old packages
#        uses: actions/delete-package-versions@v1
#        with:
#          owner: 'tausbv'
#          repo: 'data-marketplace'
#          package-name: 'net.taus.data.marketplace.data-marketplace-model'
#          num-old-versions-to-delete: 10
#          token: ${{ secrets.CI_TOKEN }}
