interface ImportMetaEnv {
  VITE_APP_API_BASE_URL: string;
  VITE_APP_EXPRESS_SERVER_URL: string;
  VITE_APP_STRIPE_PUBLISHABLE_KEY: string;
  VITE_APP_TRANSFERWISE_ACCESS_TOKEN: string;
  VITE_APP_TRANSFERWISE_API_URL: string;
  VITE_APP_PAYPAL_KEY: string;
  VITE_APP_PAYPAL_DISABLED_FUNDING: string;
  VITE_APP_HUBSPOT_FORM_SUBMISSION_API_URL: string;
  VITE_APP_HUBSPOT_CONTACT_US_FORM_ID: string;
  VITE_APP_HUBSPOT_CONTACT_US_FORM_PORTAL_ID: string;
  VITE_APP_CURRENCY: string;
  VITE_APP_GOOGLE_ANALYTICS_TRACKING_CODE: string;
}