ALTER TABLE language_data_availability_count
    DROP CONSTRAINT language_data_availability_count_content_type_id_fk,
    DROP CONSTRAINT language_data_availability_count_domain_id_fk,
    DROP CONSTRAINT language_data_availability_count_language_id_fk,
    DROP CONSTRAINT language_data_availability_count_language_id_fk_2,
    MODIFY COLUMN source_language_id int NULL,
    ADD COLUMN source_language_name VARCHAR(255) NULL AFTER source_language_id,
    ADD COLUMN source_language_display_name VARCHAR(255) NULL AFTER source_language_name,
    ADD COLUMN source_language_country VARCHAR(255) NULL AFTER source_language_name,
    ADD COLUMN source_language_display_country VARCHAR(255) NULL AFTER source_language_country,
    ADD COLUMN source_language_tag VARCHAR(255) NULL AFTER source_language_country,
    MODIFY COLUMN target_language_id int NULL,
    ADD COLUMN target_language_name VARCHAR(255) NULL AFTER target_language_id,
    ADD COLUMN target_language_display_name VARCHAR(255) NULL AFTER target_language_name,
    ADD COLUMN target_language_country VARCHAR(255) NULL AFTER target_language_name,
    ADD COLUMN target_language_display_country VARCHAR(255) NULL AFTER target_language_country,
    ADD COLUMN target_language_tag VARCHAR(255) NULL AFTER target_language_country,
    MODIFY COLUMN domain_id int NULL,
    ADD COLUMN domain_description VARCHAR(255) NULL AFTER domain_id,
    MODIFY COLUMN content_type_id int NULL,
    ADD COLUMN content_type_description VARCHAR(255) NULL AFTER content_type_id;
