insert into content_types(description, origin) VALUES ('Administrative', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Audiovisual', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Informative content', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Keywords/SEO', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Knowledge Base/Glossary', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Legal', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Marketing Material', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Online Help', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Other', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('R&D/Patents', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Technical Specifications', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Training Material', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('User Interface Text', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('User Manual', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('User-generated Content', 'MARKETPLACE');
insert into content_types(description, origin) VALUES ('Administrative', 'DQF');
insert into content_types(description, origin) VALUES ('Audiovisual', 'DQF');
insert into content_types(description, origin) VALUES ('Informative content', 'DQF');
insert into content_types(description, origin) VALUES ('Keywords/SEO', 'DQF');
insert into content_types(description, origin) VALUES ('Knowledge Base/Glossary', 'DQF');
insert into content_types(description, origin) VALUES ('Legal', 'DQF');
insert into content_types(description, origin) VALUES ('Marketing Material', 'DQF');
insert into content_types(description, origin) VALUES ('Online Help', 'DQF');
insert into content_types(description, origin) VALUES ('Other', 'DQF');
insert into content_types(description, origin) VALUES ('R&D/Patents', 'DQF');
insert into content_types(description, origin) VALUES ('Technical Specifications', 'DQF');
insert into content_types(description, origin) VALUES ('Training Material', 'DQF');
insert into content_types(description, origin) VALUES ('User Interface Text', 'DQF');
insert into content_types(description, origin) VALUES ('User Manual', 'DQF');
insert into content_types(description, origin) VALUES ('User-generated Content', 'DQF');
insert into content_types(description, origin) VALUES ('Financial Documentation', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Instructions for Use', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('News Announcements, Reports and Research', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Patents', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Policies, Process and Procedures', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Sales and Marketing Material', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Software Strings and Documentation', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Standards, Statutes and Regulations', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Support Content', 'DATA_CLOUD');
insert into content_types(description, origin) VALUES ('Undefined Content Type', 'DATA_CLOUD');
