insert into domains(description, origin) values ('Aerospace/Aviation', 'MARKETPLACE');
insert into domains(description, origin) values ('Automotive', 'MARKETPLACE');
insert into domains(description, origin) values ('Business Services', 'MARKETPLACE');
insert into domains(description, origin) values ('Chemicals', 'MARKETPLACE');
insert into domains(description, origin) values ('Cloud Services & Computer Software', 'MARKETPLACE');
insert into domains(description, origin) values ('Construction/Real Estate', 'MARKETPLACE');
insert into domains(description, origin) values ('Consumer Goods / Electronics & Hardware', 'MARKETPLACE');
insert into domains(description, origin) values ('Education', 'MARKETPLACE');
insert into domains(description, origin) values ('Energy - Water & Utilities', 'MARKETPLACE');
insert into domains(description, origin) values ('Engineering', 'MARKETPLACE');
insert into domains(description, origin) values ('Entertainment', 'MARKETPLACE');
insert into domains(description, origin) values ('Financial Services', 'MARKETPLACE');
insert into domains(description, origin) values ('Food Services/Agriculture', 'MARKETPLACE');
insert into domains(description, origin) values ('Healthcare/Medical Equipment & Supplies', 'MARKETPLACE');
insert into domains(description, origin) values ('Hospitality/Travel/Tourism', 'MARKETPLACE');
insert into domains(description, origin) values ('Humanities/Arts/Religion', 'MARKETPLACE');
insert into domains(description, origin) values ('Legal Services', 'MARKETPLACE');
insert into domains(description, origin) values ('Manufacturing/Industrial Electronics', 'MARKETPLACE');
insert into domains(description, origin) values ('Pharmaceuticals & Biotechnology', 'MARKETPLACE');
insert into domains(description, origin) values ('Public Sector/Non-Profit', 'MARKETPLACE');
insert into domains(description, origin) values ('Retail & Wholesale Distribution/E-Commerce', 'MARKETPLACE');
insert into domains(description, origin) values ('Transportation/Logistics', 'MARKETPLACE');
insert into domains(description, origin) values ('Undefined Sector', 'MARKETPLACE');
insert into domains(description, origin) values ('Aerospace/Aviation', 'DQF');
insert into domains(description, origin) values ('Automotive', 'DQF');
insert into domains(description, origin) values ('Business Services', 'DQF');
insert into domains(description, origin) values ('Chemicals', 'DQF');
insert into domains(description, origin) values ('Cloud Services & Computer Software', 'DQF');
insert into domains(description, origin) values ('Construction/Real Estate', 'DQF');
insert into domains(description, origin) values ('Consumer Goods / Electronics & Hardware', 'DQF');
insert into domains(description, origin) values ('Education', 'DQF');
insert into domains(description, origin) values ('Energy - Water & Utilities', 'DQF');
insert into domains(description, origin) values ('Engineering', 'DQF');
insert into domains(description, origin) values ('Entertainment', 'DQF');
insert into domains(description, origin) values ('Financial Services', 'DQF');
insert into domains(description, origin) values ('Food Services/Agriculture', 'DQF');
insert into domains(description, origin) values ('Healthcare/Medical Equipment & Supplies', 'DQF');
insert into domains(description, origin) values ('Hospitality/Travel/Tourism', 'DQF');
insert into domains(description, origin) values ('Humanities/Arts/Religion', 'DQF');
insert into domains(description, origin) values ('Legal Services', 'DQF');
insert into domains(description, origin) values ('Manufacturing/Industrial Electronics', 'DQF');
insert into domains(description, origin) values ('Pharmaceuticals & Biotechnology', 'DQF');
insert into domains(description, origin) values ('Public Sector/Non-Profit', 'DQF');
insert into domains(description, origin) values ('Retail & Wholesale Distribution/E-Commerce', 'DQF');
insert into domains(description, origin) values ('Transportation/Logistics', 'DQF');
insert into domains(description, origin) values ('Undefined Sector', 'DQF');
insert into domains(description, origin) VALUES ('Automotive Manufacturing', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Chemicals', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Computer Hardware', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Computer Software', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Consumer Electronics', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Energy, Water and Utilities', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Financials', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Healthcare', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Industrial Electronics', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Industrial Manufacturing', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Legal Services', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Leisure, Tourism, and Arts', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Medical Equipment and Supplies', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Pharmaceuticals and Biotechnology', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Professional and Business Services', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Stores and Retail Distribution', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Telecommunications', 'DATA_CLOUD');
insert into domains(description, origin) VALUES ('Undefined Sector', 'DATA_CLOUD');
