insert into data_annotations_categories(code, description, updated_at) values ('CREDITCARD', 'Credit card numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('IDENTITYCARD', 'ID card numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('LICENSECARD', 'Driver''s license numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('PASSPORT', 'Passport numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('PHONE', 'Phone numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('PLATE', 'License plate numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('SSN', 'Social security numbers', now());
insert into data_annotations_categories(code, description, updated_at) values ('MAIL', 'Email addresses', now());
insert into data_annotations_categories(code, description, updated_at) values ('URL', 'URLs', now());
insert into data_annotations_categories(code, description, updated_at) values ('PER', 'Person''s names', now());
